version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=jakew20
      - POSTGRES_PASSWORD=Fatkid06
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
