apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpcserver
  namespace: grpcserver
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: grpcserver
  template:
    metadata:
      labels:
        app: grpcserver
    spec:
      containers:
      - name: grpc-api
        image: 610855009960.dkr.ecr.us-east-1.amazonaws.com/simplebank:latest
        imagePullPolicy: Always
        ports:
        - name: grpc-port
          containerPort: 9090
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      restartPolicy: Always
