apiVersion: v1
kind: Service
metadata:
  name: grpcserver
  namespace: grpcserver
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  clusterIP: None
  selector:
    app: grpcserver